//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLin
    {
        public int id { get; set; }
        public bool del { get; set; }
        public int idproducte { get; set; }
        public int idTicket { get; set; }
        public Nullable<int> quantitat { get; set; }
        public Nullable<double> preu { get; set; }
    
        public virtual Producte Producte { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
